# Usually nx operates from root and expects all node_modules to exist there
# Hoist as much as possible, anything that cannot be hoisted will need to be
# installed into root package.json
nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs
