compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0007
    level: discard
  - code: YN0002
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
