compressionLevel: mixed

# https://github.com/lovell/sharp/issues/3975
enableGlobalCache: false

# YN0002: backend doesn't provide styled-components
# YN0007: must be built because it never has been before or the last one failed
logFilters:
  - code: YN0007
    level: discard
  - code: YN0002
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
