# docker compose up --build -d

version: "3"
services:
  backend:
    container_name: sami_backend
    image: sami/backend
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose --tries=1 --spider", "http://localhost:1337"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "1337:1337"
    networks:
      - sami
    environment:
      STRAPI_HOST: 0.0.0.0

  frontend:
    container_name: sami_frontend
    image: sami/frontend
    build:
      dockerfile: docker/frontend.dockerfile
      context: .
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "1337:1337"
    networks:
      - sami
    environment:
      NEXT_PUBLIC_API_URL: backend:1337

volumes:
  strapi-data:

networks:
  sami:
    name: Sami
    driver: bridge
