# docker compose -p sami-website -f docker/docker-compose.yml up

version: "3"
services:
  backend:
    container_name: backend
    # NOTE - Built via `yarn build` script
    image: sami/backend:latest
    # command: "/bin/ash -c 'while sleep 3600; do :; done'"
    restart: unless-stopped

    # Any variables set here take precedence over the .env file
    environment:
      STRAPI_HOST: 0.0.0.0
    ports:
      # Expose on 127.0.0.1 instead of default 0.0.0.0 as next.js rewrites localhost to this
      # https://earthly.dev/blog/youre-using-docker-compose-wrong/
      # https://github.com/vercel/next.js/issues/27865
      # NOTE - might not work in WSL (?) https://github.com/docker/for-win/issues/13182
      - "1337:1337"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:1337 || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

    # TODO - save strapi data volume
    # volumes:
    #   -

  frontend:
    container_name: frontend
    # NOTE - Built via `yarn build` script
    image: sami/frontend:latest

    # Healthcheck can be slow, just start optimistically

    # depends_on:
    #   backend:
    #     condition: service_healthy

    # command: "/bin/ash -c 'while sleep 3600; do :; done'"
    # restart: unless-stopped

    # NOTE - env vars not passed to running instance as inlined during build
    # a hacky workaround to populate exists in the next.config.js file

    environment:
      NEXT_PUBLIC_API_URL: http://backend:1337
    ports:
      - "3000:3000"
