# docker build --target frontend --tag sami/backend -f docker\Dockerfile .
# docker run -it --rm --name sami-backend -p 1337:1337 sami/backend

# Setup Buildx builder
# syntax=docker/dockerfile:1
FROM docker
COPY --from=docker/buildx-bin /buildx /usr/libexec/docker/cli-plugins/docker-buildx
RUN docker buildx version

FROM sami/base as backend-builder
COPY backend ./backend

ARG ENV_NAME=production 
ENV NODE_ENV=${ENV_NAME}
RUN yarn workspace backend build

# Build frontend
FROM sami/base as frontend-builder
COPY ./frontend ./frontend
RUN yarn workspace frontend build:standalone


FROM node:18-alpine

# Backend
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
RUN rm -rf /var/cache/apk/*

ARG ENV_NAME=production 
ENV NODE_ENV=${ENV_NAME}
WORKDIR /app
COPY --from=backend-builder /app/backend ./backend

# Frontend
COPY --from=frontend-builder /app/frontend/public ./frontend/public
COPY --from=frontend-builder /app/frontend/.next/standalone/frontend ./frontend
COPY --from=frontend-builder /app/frontend/.next/static ./frontend/.next/static

ENV PATH /app/node_modules/.bin:$PATH
ENV HOST 0.0.0.0
EXPOSE 1337
EXPOSE 3000

# TODO - organise nested folders and child commands
CMD ["strapi","start","&","node", "server.js"]

# debug cmd
# "/bin/ash -c 'while sleep 3600; do :; done'"