############# Run Via CLI #################
# yarn scripts docker build --only base
# docker compose -f docker-compose.server.yml -p sami-next up

# TODO - add common logging methods

services:
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: sami_webserver
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     # Custom virtual host overrides
  #     - ./docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
  #     # Generated default and global override conf
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  #     # SSL Certs
  #     - html:/usr/share/nginx/html
  #     - dhparam:/etc/nginx/dhparam
  #     - ./docker/nginx/certs:/etc/nginx/certs:ro
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - webserver

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   environment:
  #     NGINX_PROXY_CONTAINER: sami_webserver
  #     # Testing certs
  #     ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
  #   volumes:
  #     - ./docker/nginx/certs:/etc/nginx/certs:rw
  #     - acme:/etc/acme.sh
  #     - html:/usr/share/nginx/html
  #     - dhparam:/etc/nginx/dhparam
  #     - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  repo:
    container_name: sami_repo
    image: samicharity/base:latest
    # command: "/bin/ash -c 'while sleep 3600; do :; done'"
    restart: unless-stopped
    ports:
      - "1337:1337"
      - "3000:3000"
    command: "./scripts/node_modules/.bin/pm2-runtime start pm2.config.js"
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 4GB
    # volumes:
    #   # Uploads folder shared between frontend and backend for easier access
    #   - ./docker/data/uploads:/app/public/uploads
    #   - ./docker/data/db:/app/db
    #   # TODO - persist db data (possibly just use db image to allow connect)
    #   # - /app/backend/sami-dev.db
    volumes:
      - ./pm2.config.js:/app/pm2.config.js
      - ./config/docker.env:/app/config/docker.env
      - ./docker/data/uploads:/app/backend/public/uploads
      - ./docker/data/db:/app/db
      # - ./backend/build:/app/backend/build
    env_file:
      - ./config/docker.env
      - ./config/docker.local.env
    environment:
      - DATABASE_FILENAME=db/sami-docker.db
      # Load docker configuration
      - NODE_ENV=docker
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:1337 || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - webserver

    # volumes:
    #   # Uploads folder shared between frontend and backend for easier access
    #   - ./docker/data/uploads:/app/public/uploads
    # environment:
    #   VIRTUAL_HOST: ${PUBLIC_DOMAIN}
    #   VIRTUAL_PORT: "3000"
    #   # TODO - configure for production and env vars
    #   LETSENCRYPT_HOST: ${PUBLIC_DOMAIN}
    #   LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  webserver:

volumes:
  html:
  dhparam:
  certs:
  acme:

  # TODO find a way to run nginx reverse proxy and dashboard on path
  # https://docs.strapi.io/dev-docs/deployment/nginx-proxy
  # https://forum.strapi.io/t/strapi-in-subfolder-issue/13401/4
#######################################################################################
# Legacy Notes - to confirm if still required
#######################################################################################
# Expose on 127.0.0.1 instead of default 0.0.0.0 as next.js rewrites localhost to this
# https://earthly.dev/blog/youre-using-docker-compose-wrong/
# https://github.com/vercel/next.js/issues/27865
# NOTE - might not work in WSL (?) https://github.com/docker/for-win/issues/13182

#######################################################################################
# Deprecated - use build from cli instead of compose (to ensure base builds correctly)
#######################################################################################
# build:
#   dockerfile: ./docker/base.dockerfile
#   tags:
#     - "samicharity/base:1.0.0"
