# Basic test to ensure PRs pass lint build. Default runner except when preview deployment already generated
name: Lint and Build
on:
  pull_request:
    branches:
      - main
concurrency:
  group: lint-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    if: '!contains(fromJSON(github.event.pull_request.labels.*.name), "Test - preview")'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
          cache: "yarn"

      - name: Install node modules
        run: yarn install --immutable

      #############################################################################
      #         Lint, Setup and Build
      #############################################################################
      - name: Lint Code
        run: yarn lint
      - name: Bootstrap Strapi
        run: |
          yarn scripts strapi bootstrap --environment development
          yarn scripts strapi import --environment development
      - name: Build
        run: yarn build --no-export --no-preview --no-deploy
